version: '3.1'

services:

  db:
    image: mysql:8.2
    container_name: mysql_db_test
    restart: always
    ports:
      - '9010:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testData
      TZ: America/Bogota
    volumes:
      - ./db_data:/var/lib/mysql
    
